language: node_js
node_js:
  - "8"
cache:
  - functions/node_modules
branches:
  only:
  - master
before_script:
  - npm i -g firebase-tools@latest
script:
  - firebase use default --token $FIREBASE_DEPLOY_KEY
  - firebase deploy -m "build $TRAVIS_BUILD_NUMBER" --non-interactive --force --token $FIREBASE_DEPLOY_KEY
